name: quiz
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/logoblack.png
    - assets/question.png    
    - assets/AZ.png
    - assets/dark.svg
    - assets/KTK dark green logo.svg
    - assets/KTK light logo.svg
    - assets/KTK white-ish logo.svg
    - assets/darkab.png
    - assets/facebook.png
    - assets/high.png
    - assets/new.png
    - assets/splashlogo.png
    - assets/a.png

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LeagueSpartan-Black.ttf
          weight: 900
        - asset: assets/fonts/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LeagueSpartan-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
  image_path: "assets/a.png"
  name: "KTK"  